config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users do
    collection { get 'search' }
  end
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages
  accepts_nested_attributes_for :users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  def to_json
    { name: user.name,
      created_at: created_at,
      body: body,
      image: image.url }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, :authenticate_user!

  def configure_permitted_parameters
    if devise_controller?
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]
  def index
    @message = Message.new
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(create_params)
    if @group.save
      redirect_to :root, flash[:notice] = { alert: "グループを作成できました" }
    else
      redirect_to new_group_path, flash[:alert] = { alert: "グループを作成できませんでした" }
    end
  end

  def edit
  end

  def update
    if @group.update(create_params)
      redirect_to :root, flash[:notice] = { alert: "変更を登録しました" }
    else
      redirect_to edit_group_path, flash[:alert] = { alert: "変更を登録できませんでした" }
    end
  end

  private

  def create_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
   @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @groups = Group.all
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user)
    @message = Message.new
    respond_to do |format|
      format.any
      format.json { render json: @messages.map { |message| message.to_json } }
    end
  end

  def new
  end

  def create
    @message = current_user.messages.new(create_params)
    message = @message.body
    if @message.save
      respond_to do |format|
        format.any
        format.json { render json:
          { message:
            { name: @message.user.name,
              created_at: @message.created_at,
              body: @message.body,
              image: @message.image.url } } }
      end
      flash[:notice] = "メッセージを送信しました"
    else
      flash[:alert] = "メッセージを送信できませんでした"
    end
  end

  private

  def create_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def search
    @users = User.where('name LIKE(?)', "%#{params[:user][:text]}%")
    respond_to do |format|
      format.any
      format.json { render json: @users }
    end
  end
end

app/views/common/_alert.html.haml
-if notice
  %p.alert.alert-notice
  = notice

-if alert
  %p.alert.alert-error
  = alert

app/views/groups/_group.html.haml
%li.chat-groups
= link_to group_messages_path(group), class: 'chat-group__link' do
  %p.chat-group__name
  = group.name
%p.chat-group__message

app/views/groups/_side_bar.html.haml
.chat-side
  .chat-user.clearfix
    %h5
      moeri
    .chat-user__actions
      = link_to new_group_path, class: 'chat-user__action' do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_registration_path, class: 'chat-user__action' do
        %i.fa.fa-cog
  %ul.chat-groups
  = render groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :グループ名, class: 'chat-group-form__label', for: "chat_group_name"
      .chat-group-form__field--right
        = f.text_field :name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバーを追加, class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ placeholder: "追加したいユーザー名を入力してください", type: "text" }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, class:'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
= render partial: 'groups/side_bar', locals: { groups: @groups }

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :グループ名, class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, id: "chat_group_name", class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバーを追加, class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ placeholder: "追加したいユーザー名を入力してください" }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, class:'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            %p.chat-group-user__name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: "chat-group-form__action-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'common/alert'
    = yield

app/views/messages/_message.html.haml
%li.chat-message
  .chat-message__header.clearfix
    %p.chat-message_name
      = message.user.name
    %p.chat-message_time
      = message.created_at
  %p.chat-message_body
    = message.body
    = image_tag(message.image)

app/views/messages/index.html.haml
.layout-notification
.chat
  = render partial: 'groups/side_bar', locals: { groups: @groups}
  .chat-main
    .chat-header.clearfix
      .chat-header--left
        %h2
        = @group.name
        %p.chat-header__users
          Members:
          %span.chat-header__user
          - @group.users.each do |user|
            = user.name
      .chat-header--right
        = link_to "Edit", edit_group_path(@group), class: 'chat-header__edit-btn'

    .chat-body
      %ul.chat-messages
        = render @messages
    .chat-footer
      = form_for [@group, @message] do |f|
        .chat-footer__body
          = f.text_area :body, placeholder: 'type a message'
          .chat-footer__file
            = f.label :image do
              = f.file_field :image
              %i.fa.fa-image
        = f.submit 'Send'